import type { BoardState, GameEvent, GameStore, MatchState, Side, Tile } from "@domino/shared";
import { canPlay, passTurn, playTile } from "@domino/shared/src/game";

// ---------------------------------------------------------------------------
// Bot configuration: players p1, p2, p3 are bots; p0 is the human
// ---------------------------------------------------------------------------

const HUMAN_PLAYER_ID = "p0";

// ---------------------------------------------------------------------------
// Bot AI — finds the best valid move for a given hand and board
// ---------------------------------------------------------------------------

/**
 * Finds a valid move for a bot player.
 *
 * Strategy (simple for now):
 * 1. If the board is empty, play the first valid tile (any tile).
 * 2. Search the hand for valid tiles on either side.
 * 3. Prefer doubles (they block more).
 * 4. Otherwise, play the first valid tile found.
 *
 * @returns The chosen tile ID and side, or `null` if the bot must pass
 */
export function findBotMove(
	hand: Tile[],
	board: BoardState,
): { tileId: string; side: Side } | null {
	if (hand.length === 0) return null;

	// Board is empty — play any tile, prefer doubles
	if (board.leftEnd === null && board.rightEnd === null) {
		// Prefer doubles first
		for (const tile of hand) {
			if (tile.top === tile.bottom) {
				return { tileId: tile.id, side: "right" };
			}
		}
		return { tileId: hand[0].id, side: "right" };
	}

	// Non-empty board: collect all valid moves
	const validMoves: Array<{ tileId: string; side: Side; tile: Tile }> = [];

	for (const tile of hand) {
		// Skip if tile is not in a valid state (shouldn't happen)
		if (canPlay(tile, "left", board)) {
			validMoves.push({ tileId: tile.id, side: "left", tile });
		}
		if (canPlay(tile, "right", board)) {
			validMoves.push({ tileId: tile.id, side: "right", tile });
		}
	}

	if (validMoves.length === 0) return null;

	// Sorting heuristic: prefer doubles, then higher pip tiles
	// This is intentionally simple — can be replaced with minimax later
	validMoves.sort((a, b) => {
		const aScore =
			(a.tile.top + a.tile.bottom) * 10 + (a.tile.top === a.tile.bottom ? 100 : 0);
		const bScore =
			(b.tile.top + b.tile.bottom) * 10 + (b.tile.top === b.tile.bottom ? 100 : 0);
		return bScore - aScore; // descending: highest score first
	});

	return { tileId: validMoves[0].tileId, side: validMoves[0].side };
}

// ---------------------------------------------------------------------------
// Bot turn execution
// ---------------------------------------------------------------------------

/**
 * Checks if the current player of the match is a bot (not p0).
 */
export function isCurrentTurnBot(match: MatchState): boolean {
	const currentPlayer = match.players[match.turn.currentTurn];
	return currentPlayer.id !== HUMAN_PLAYER_ID;
}

/**
 * Executes bot turns one after another until it's the human's turn
 * or the match ends.
 *
 * @returns All events generated by bot moves
 */
export function executeBotTurns(
	store: GameStore,
	matchId: string,
): { events: GameEvent[] } {
	const allEvents: GameEvent[] = [];

	// eslint-disable-next-line no-constant-condition
	while (true) {
		const match = store.getGame(matchId);
		if (match?.status !== "in_progress") break;

		if (!isCurrentTurnBot(match)) break;

		const currentPlayer = match.players[match.turn.currentTurn];

		// Safety: if the bot has no tiles, we can't pass (passTurn on empty hand
		// returns an error without advancing the turn, causing an infinite loop).
		// This shouldn't happen in a real game because the hand ends when a player
		// empties their hand, but guard against it.
		if (currentPlayer.hand.length === 0) break;

		const move = findBotMove(currentPlayer.hand, match.board);

		let result: import("@domino/shared").ActionResult;
		if (move) {
			result = playTile(match, currentPlayer.id, move.tileId, move.side);
		} else {
			result = passTurn(match, currentPlayer.id);
		}

		// Persist updated state
		if (result.match !== match) {
			store.updateGame(matchId, result.match);
		}

		allEvents.push(...result.events);

		// Stop if the match ended
		if (result.match.status !== "in_progress") break;
	}

	return { events: allEvents };
}
